#!/bin/bash

# Function to display information about a specific subdomain
get_subdomain_info() {
    domain="$1"
    subdomain="$2"
    dig_output=$(dig "$subdomain.$domain" | awk '/ANSWER SECTION:/ {getline; print}')
    record_type=$(echo "$dig_output" | awk '{print $4}')
    destination=$(echo "$dig_output" | awk '{print $5}')
    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

# Main script
domain="$1"
subdomain="$2"

if [ -z "$subdomain" ]; then
    # Display information for default subdomains
    default_subdomains=("www" "lb-01" "web-01" "web-02")
    for sub in "${default_subdomains[@]}"; do
        get_subdomain_info "$domain" "$sub"
    done
else
    # Display information for the specified subdomain
    get_subdomain_info "$domain" "$subdomain"
fi
