#!/usr/bin/env bash
# print domains and subdomains

print_domain_subdomain () {
    local query_result
    query_result=$(dig "$1" +short)
    if [[ -n "$query_result" ]]; then
        echo "The subdomain $2 is an A record and points to $query_result"
    else
        echo "No record found for subdomain $2"
    fi
}

if [ "$#" -eq 2 ]; then
    print_domain_subdomain "$2.$1" "$2"
else
    print_domain_subdomain "www.$1" "www"
    print_domain_subdomain "lb-01.$1" "lb-01"
    print_domain_subdomain "web-01.$1" "web-01"
    print_domain_subdomain "web-02.$1" "web-02"
fi
