#!/usr/bin/env bash
# This script installs and configures Nginx web server

apt-get update -y
apt-get install nginx -y
sudo ufw allow "Nginx HTTP"
sudo chown -R $USER:$USER /var/www/html/index.nginx-debian.html
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
