#!/usr/bin/env bash
# This script configures Nginx to have a custom 404 page

# Update package index and install Nginx silently
apt-get update -y
apt-get install nginx -y

# Create a custom 404 page with the required string
echo "Ceci n'est pas une page" > /usr/share/nginx/html/404.html

# Modify Nginx default configuration to use the custom 404 page
sed -i '/server_name _;/a \\n\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}' /etc/nginx/sites-available/default

# Restart Nginx
service nginx restart
