#!/usr/bin/env bash
# Script to kill the 7-highlander process

# Find the PID of the 7-highlander process using pgrep and the script name
PID=$(pgrep -f '7-highlander')

# If the PID was found, kill the process
if [[ ! -z $PID ]]; then
  kill "$PID"
  echo "7-highlander process ($PID) has been killed."
else
  echo "7-highlander process not found."
fi
