#!/bin/bash

# Update package repositories
sudo apt-get update

# Install ufw (if not already installed)
sudo apt-get install ufw -y

# Set default policies
sudo ufw default deny incoming
sudo ufw default allow outgoing

# Allow incoming SSH (port 22)
sudo ufw allow 22/tcp

# Allow incoming HTTPS (port 443)
sudo ufw allow 443/tcp

# Allow incoming HTTP (port 80)
sudo ufw allow 80/tcp

# Enable ufw
sudo ufw enable

